use POKEMONS;

-- Finde alle Pokemon die als Attacke nur Feuer-Attacken haben



SELECT *
FROM POKEMON_BT PB
WHERE EXISTS(
    SELECT 1
    FROM LEARNABLE_MOVES_JT LMJ
    JOIN MOVES M ON M.MOVE_ID = LMJ.MOVE_ID
    WHERE M.SPECIES_TYPE = 'fire' AND LMJ.POKEMON_ID = PB.POKEMON_ID
)
AND NOT EXISTS (
    SELECT 1
    FROM LEARNABLE_MOVES_JT LMJ
    JOIN MOVES M ON M.MOVE_ID = LMJ.MOVE_ID
    WHERE M.SPECIES_TYPE <> 'fire' AND LMJ.POKEMON_ID = PB.POKEMON_ID
);

-- Finde alle Pokemon die nur einen Attacken-Typ haben. z.B. nur Luft-Attacken

SELECT
    PBT.*
FROM
    LEARNABLE_MOVES_JT LM
    JOIN MOVES M on M.MOVE_ID = LM.MOVE_ID
    JOIN ORIGIN_POKEMON OG on OG.POKEMON_ID = LM.POKEMON_ID
    JOIN POKEMON_BT PBT on PBT.POKEMON_ID = OG.POKEMON_ID
GROUP BY LM.POKEMON_ID
HAVING count(distinct M.SPECIES_TYPE) = 1
;