use convoy;

CREATE TABLE CONVOYCOMPONET
(
    ID   INT AUTO_INCREMENT,
    CODE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TRUCK
(
    ID       INT,
    CAPACITY INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE WAGGON
(
    ID INT,
    PRIMARY KEY (ID)
);

ALTER TABLE TRUCK
    ADD CONSTRAINT FK_TRUCKS_ID FOREIGN KEY (ID) REFERENCES CONVOYCOMPONET (ID) ON DELETE CASCADE;
ALTER TABLE WAGGON
    ADD CONSTRAINT FK_WAGGONS_ID FOREIGN KEY (ID) REFERENCES CONVOYCOMPONET (ID) ON DELETE CASCADE;
-- Wenn Spalte Unique Constraint hat dann weiß es, dass es 1:1 ist

ALTER TABLE TRUCK RENAME TRUCKS;
ALTER TABLE WAGGON RENAME WAGGONS;
ALTER TABLE CONVOYCOMPONET RENAME CONVOYCOMPONETS_BT;

ALTER TABLE WAGGONS
    ADD TRUCK_ID INT;
ALTER TABLE WAGGONS
    ADD CONSTRAINT FK_WAGGONS_TRUCKID FOREIGN KEY (TRUCK_ID) REFERENCES TRUCKS (ID);

-- INSERTS

INSERT INTO CONVOYCOMPONETS_BT (CODE)
VALUES ('TEST1');
INSERT INTO CONVOYCOMPONETS_BT (CODE)
VALUES ('TEST2');
INSERT INTO CONVOYCOMPONETS_BT (CODE)
VALUES ('TEST3');
INSERT INTO CONVOYCOMPONETS_BT (CODE)
VALUES ('TEST4');
INSERT INTO CONVOYCOMPONETS_BT (CODE)
VALUES ('TEST5');
INSERT INTO CONVOYCOMPONETS_BT (CODE)
VALUES ('TEST6');
INSERT INTO CONVOYCOMPONETS_BT (CODE)
VALUES ('TEST7');

INSERT INTO TRUCKS (ID, CAPACITY)
VALUES (1, 10);
INSERT INTO TRUCKS (ID, CAPACITY)
VALUES (2, 10);
INSERT INTO TRUCKS (ID, CAPACITY)
VALUES (3, 10);

INSERT INTO WAGGONS (ID, TRUCK_ID)
VALUES (4, 1);
INSERT INTO WAGGONS (ID, TRUCK_ID)
VALUES (5, 3);
INSERT INTO WAGGONS (ID)
VALUES (6);
INSERT INTO WAGGONS (ID, TRUCK_ID)
VALUES (7, 3);


SELECT CODE,
       case
           when t.ID is null then 'WAGGONS'
           else 'TRUCKS'
           end TYPE
from CONVOYCOMPONETS_BT c
         left join TRUCKS t on c.ID = t.ID
         left join WAGGONS w on c.ID = w.ID;

-- muss mit union gemacht werden
SELECT CODE, 'WAGGON'
FROM WAGGONS
        join CONVOYCOMPONETS_BT cb on cb.ID = WAGGONS.ID
union
SELECT CODE, 'TRUCK'
FROM TRUCKS
         join CONVOYCOMPONETS_BT c on c.ID = TRUCKS.ID;

-- alle trucks die zumindest 1 waggon haben
-- mit exists machen

select DISTINCT T.ID
from TRUCKS T join WAGGONS W on T.ID = W.TRUCK_ID;

select *
from TRUCKS T where EXISTS(select * from WAGGONS W where  T.ID = W.TRUCK_ID);